import { EntryData } from "../../shared/models/entrydata.model";



export const ENTRYDATASAMPLE: EntryData[] = [
  {
    stationId: '1',
    elementId: 1,
    dataSourceId: 3,
    level: "surface",
    year: 2023,
    month: 6,
    day: 9,
    hour: 0,
    //dateTime: "2021-01-01 06:00:00",
    value: "250",
    flag: "",
    paperImage: "file_name",
    qcStatus: 0,
    changesLog: "changes_in_json"
  },
  {
    stationId: '1',
    elementId: 2,
    dataSourceId: 3,
    level: "surface",
    year: 2023,
    month: 6,
    day: 9,
    hour: 6,
    //dateTime: "2021-01-01 06:00:00",
    value: "300",
    flag: "",
    paperImage: "file_name",
    qcStatus: 0,
    changesLog: "changes_in_json"
  },
  {
    stationId: '1',
    elementId: 3,
    dataSourceId: 3,
    level: "surface",
    year: 2021,
    month: 1,
    day: 1,
    hour: 6,
    //dateTime: "2021-01-01 06:00:00",
    value: "400",
    flag: "D",
    paperImage: "file_name",
    qcStatus: 0,
    changesLog: "changes_in_json"
  },
  {
    stationId: '1',
    elementId: 4,
    dataSourceId: 3,
    level: "surface",
    year: 2021,
    month: 1,
    day: 1,
    hour: 6,
    //dateTime: "2021-01-01 06:00:00",
    value: "100",
    flag: "S",
    paperImage: "file_name",
    qcStatus: 0,
    changesLog: "changes_in_json"
  },
  {
    stationId: '2',
    elementId: 1,
    dataSourceId: 3,
    level: "surface",
    year: 2021,
    month: 1,
    day: 1,
    hour: 6,
    //dateTime: "2021-01-01 06:00:00",
    value: "256",
    flag: "",
    paperImage: "file_name",
    qcStatus: 0,
    changesLog: "changes_in_json"
  },
  {
    stationId: '2',
    elementId: 2,
    dataSourceId: 3,
    level: "surface",
    year: 2021,
    month: 1,
    day: 1,
    hour: 6,
    //dateTime: "2021-01-01 06:00:00",
    value: "320",
    flag: "",
    paperImage: "file_name",
    qcStatus: 0,
    changesLog: "changes_in_json"
  },
  {
    stationId: '3',
    elementId: 3,
    dataSourceId: 2,
    level: "surface",
    year: 2021,
    month: 1,
    day: 1,
    hour: 6,
    //dateTime: "2021-01-01 06:00:00",
    value: "620",
    flag: "D",
    paperImage: "file_name",
    qcStatus: 0,
    changesLog: "changes_in_json"
  },
  {
    stationId: '3',
    elementId: 1,
    dataSourceId: 2,
    level: "surface",
    year: 2021,
    month: 1,
    day: 1,
    hour: 6,
    //dateTime: "2021-01-01 06:00:00",
    value: "151",
    flag: "",
    paperImage: "file_name",
    qcStatus: 0,
    changesLog: "changes_in_json"
  },
  {
    stationId: '3',
    elementId: 2,
    dataSourceId: 2,
    level: "surface",
    year: 2021,
    month: 1,
    day: 1,
    hour: 6,
    //dateTime: "2021-01-01 06:00:00",
    value: "120",
    flag: "",
    paperImage: "file_name",
    qcStatus: 0,
    changesLog: "changes_in_json"
  },
  {
    stationId: '3',
    elementId: 3,
    dataSourceId: 2,
    level: "surface",
    year: 2021,
    month: 1,
    day: 1,
    hour: 6,
    //dateTime: "2021-01-01 06:00:00",
    value: '100',
    flag: "D",
    paperImage: "file_name",
    qcStatus: 0,
    changesLog: "changes_in_json"
  },
  {
    stationId: '3',
    elementId: 4,
    dataSourceId: 3,
    level: "surface",
    year: 2021,
    month: 1,
    day: 1,
    hour: 6,
    //dateTime: "2021-01-01 06:00:00",
    value: "700",
    flag: "S",
    paperImage: "file_name",
    qcStatus: 0,
    changesLog: "changes_in_json"
  }

]


